#ifndef _OPEN_METEO_H_
#define _OPEN_METEO_H_

/*
 * FILE AUTOGENERATED BY cbindgen. DO NOT EDIT
 * https://github.com/mozilla/cbindgen
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct open_meteo_client_t open_meteo_client_t;

typedef struct open_meteo_options_t open_meteo_options_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct open_meteo_client_t *open_meteo_client_new(void);

void open_meteo_client_free(struct open_meteo_client_t *client);

struct open_meteo_options_t *open_meteo_forecast_options_new(void);

void open_meteo_forecast_options_set_location(struct open_meteo_options_t *options,
                                              double lat,
                                              double lng);

char *open_meteo_client_forecast(struct open_meteo_client_t *client,
                                 struct open_meteo_options_t *opts);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _OPEN_METEO_H_ */
