#ifndef _OPEN_METEO_H_
#define _OPEN_METEO_H_

/*
 * FILE AUTOGENERATED BY cbindgen. DO NOT EDIT
 * https://github.com/mozilla/cbindgen
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct open_meteo_client_t open_meteo_client_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct open_meteo_client_t *open_meteo_client_new(void);

void open_meteo_client_free(struct open_meteo_client_t *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* _OPEN_METEO_H_ */
